name    'desalvo-nis'
version '0.1.2'
source 'https://github.com/desalvo/puppet-nis'
author 'desalvo'
license 'Apache License, Version 2.0'
summary 'Puppet module for NIS management'
description 'A puppet module for managing NIS client and servers'
project_page 'https://github.com/desalvo/puppet-nis'
dependency 'desalvo/rpcbind', '>= 0.1.0'
